# Generated by Django 3.2.25 on 2025-01-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=70)),
                ('date', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('allocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.allocate')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=60)),
                ('dist', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('dob', models.CharField(max_length=70)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('usertype', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('Opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.opportunities')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=60)),
                ('no_seats', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Seattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(max_length=60)),
                ('desc', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_name', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=70)),
                ('pin', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.community')),
  
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.CharField(max_length=70)),
                ('seat_number', models.CharField(max_length=70)),
                ('rate', models.CharField(max_length=70)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.screen')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.seattype')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('venue', models.CharField(max_length=60)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='Requestimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=60)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.request')),
            ],
        ),
        
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
              
                ('name', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('images', models.FileField(upload_to='')),
                ('videos', models.FileField(upload_to='')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.production')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=60)),
                ('Opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.opportunities')),
            ],
        ),
        migrations.CreateModel(
            name='join_community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer')),

            ],
        ),
         migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=70)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.booking')),
            ],
        ),
        migrations.AddField(
            model_name='opportunities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.projects'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=60)),
                ('film_release', models.CharField(max_length=70)),
                ('film_desc', models.CharField(max_length=70)),
                ('image', models.FileField(upload_to='')),

                ('duration', models.CharField(max_length=70)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.type')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.login'),
        ),
        migrations.CreateModel(
            name='Bookingchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=70)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.booking')),
                ('seating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.seating')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.customer'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.film'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.screen'),
        ),
        migrations.AddField(
            model_name='allocate',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_app.timing'),
        ),
    ]
