# Generated by Django 3.2.25 on 2025-01-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='videos',
        ),
    ]
